# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCriminal = QtWidgets.QMenu(self.menubar)
        self.menuCriminal.setObjectName("menuCriminal")
        self.menuCivil = QtWidgets.QMenu(self.menubar)
        self.menuCivil.setObjectName("menuCivil")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFinal_Judgment_Entry = QtWidgets.QAction(MainWindow)
        self.actionFinal_Judgment_Entry.setObjectName("actionFinal_Judgment_Entry")
        self.actionBond_Sheet = QtWidgets.QAction(MainWindow)
        self.actionBond_Sheet.setObjectName("actionBond_Sheet")
        self.actionFailure_to_Appear = QtWidgets.QAction(MainWindow)
        self.actionFailure_to_Appear.setObjectName("actionFailure_to_Appear")
        self.actionNew_Entry = QtWidgets.QAction(MainWindow)
        self.actionNew_Entry.setObjectName("actionNew_Entry")
        self.actionLien_Entry = QtWidgets.QAction(MainWindow)
        self.actionLien_Entry.setObjectName("actionLien_Entry")
        self.menuFile.addAction(self.actionNew_Entry)
        self.menuCriminal.addAction(self.actionFinal_Judgment_Entry)
        self.menuCriminal.addAction(self.actionBond_Sheet)
        self.menuCriminal.addAction(self.actionFailure_to_Appear)
        self.menuCivil.addAction(self.actionLien_Entry)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCriminal.menuAction())
        self.menubar.addAction(self.menuCivil.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Entry Master"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCriminal.setTitle(_translate("MainWindow", "Criminal"))
        self.menuCivil.setTitle(_translate("MainWindow", "Civil"))
        self.actionFinal_Judgment_Entry.setText(_translate("MainWindow", "Final Judgment Entry"))
        self.actionBond_Sheet.setText(_translate("MainWindow", "Bond Sheet"))
        self.actionFailure_to_Appear.setText(_translate("MainWindow", "Failure to Appear"))
        self.actionNew_Entry.setText(_translate("MainWindow", "New Entry"))
        self.actionLien_Entry.setText(_translate("MainWindow", "Lien Entry"))
